### ISSUE TITLE
Gem has randomly stopped working

### ISSUE THREAD

**Issue by drcongo** [atech/Codebase4-Gem#5]
I've integrated the gem with our fabric deploys with a python function that constructs a shell call to something along the lines of `cb deploy f5244d6 08f2ce6 -e production -s https://my.project.domain -b master -r project-name:repo-name -h myaccount.codebasehq.com --protocol https`

Recently it has stopped working for me though, with the following stack trace...

```
/usr/local/lib/ruby/gems/2.4.0/gems/codebase4-1.0.17/lib/codebase.rb:36:in `request': An HTTP error occured (Net::HTTPForbidden) (RuntimeError)
    from /usr/local/lib/ruby/gems/2.4.0/gems/codebase4-1.0.17/lib/codebase/cli.rb:84:in `deploy'
    from /usr/local/lib/ruby/gems/2.4.0/gems/codebase4-1.0.17/lib/codebase/cli.rb:14:in `invoke'
    from /usr/local/lib/ruby/gems/2.4.0/gems/codebase4-1.0.17/bin/cb:3:in `<top (required)>'
    from /usr/local/bin/cb:22:in `load'
    from /usr/local/bin/cb:22:in `<main>'
```

I've tried uninstalling and re-installing but to no avail.

**Comment by drcongo** [comment]
PS. This step in the instructions has always failed `cb test mydomain.codebasehq.com`, but actually sending the deploy to Codebase worked anyway.

**Comment by drcongo** [comment]
Can we assume from this that this project is dead?
